### ISSUE TITLE
urxvt term colors issue

### ISSUE THREAD

**Issue by nkoturovic** [a-n-t-h-o-n-y/CPPurses#21] opened 2019-02-25 15:34 UTC
## Description
After executing any cppurses tui program in some terminal emulators (tested with multiple versions of `urxvt`, and `st`(simple terminal)) some of the terminal colors get modified.
Colors: 239-254 after end of program execution (with or without interrupt) look different.
Screenshot: [terminal color test](https://ibb.co/gRsmdpB)
I'm using Arch Linux
Tried with following packages:
## URXVT
1) community/rxvt-unicode (9.22-7)
2) aur/rxvt-unicode-intensityfix (9.22-12)
## st - Simple Terminal
3) aur/st (0.8.1-1)
## Additional info
st (Simple terminal) logs to stderr:
```sh
# at cppurses program execution start
erresc: unknown csi ESC[22;0;0t
# at cppurses program end
erresc: invalid color (null)
erresc: unknown csi ESC[23;0;0t
```
- On the other hand, using some other terminal emulators: `lxterminal` or `xterm` issue described above does not occur.

**Comment by a-n-t-h-o-n-y** [comment] 2019-02-27 19:27
The latest commits in the develop branch should patch up the color differences for normal exit and on SIGINT
fa13145f4d670489bf3a142526d533a6758ae24f

I can't get the stderr to reproduce on st, I did remove an environment variable that was being set by the library to force ncurses to use xterm-256color control sequences, that might have had something to do with it. Removing this seems to not allow ncurses to change color definitions on st, so you'd have to set the TERM variable yourself before running the program if this occurs. `TERM="xterm-256color"`

**Comment by kotur95** [comment] 2019-02-27 23:26
I think that assumption you've made is right. According to [this](https://invisible-island.net/ncurses/terminfo.src.html#toc-_R_X_V_T) `urxvt` and `xterm` control sequences differ. If I'm correct, these differences should be resolved by `Terminfo` library/database which is used and comes with `ncurses`.

I've tested demos from devel branch, and now everything seems to work just fine with `URxvt`.

St behaved as you described, but installing newer version of st from `AUR`. (`aur/st-git 1:0.7.9.g8c99915-1`)
Additional terminfo files got generated by package: located in /home/$USER/.terminfo/s/ besides the usual ones which were located at (/usr/share/terminfo/s/) -> and provided by ncurses::terminfo.. Removing new (package generated) st terminfo files, the home directory ones, it switched to using old ones and behaved incorrectly.

**Comment by kotur95** [comment] 2019-02-27 23:31
Closed it unintentionally, commenting to reopen.

**Comment by kotur95** [comment] 2019-02-28 02:17
Accidentally closed issue, sorry for that.

After fix: https://github.com/a-n-t-h-o-n-y/CPPurses/commit/fa13145f4d670489bf3a142526d533a6758ae24f
I have noticed probably unwanted behavior (because of relying on initscr() which relays on $TERM properly set). Next example results in error:
```bash
TERM="foo"  # Change $TERM to foo
./demo # executing cppurses demo
# Instead of executing (error prints -> from ncurses::initscr())
Error opening terminal: foo.   # With exit code (1)
```
Tried to fix it with this patch: https://github.com/a-n-t-h-o-n-y/CPPurses/pull/22
1) If could initialize with `$TERM`  -> okay
2) if not then -> Try to initialize with xterm-256color
3) if both failed then -> Handle error (TODO)

**INFO**: Some terminfo files are not written correctly, that causes the problems like one occurred with `st` after your patch .. That should be researched more to find an appropriate solution.

**Comment by a-n-t-h-o-n-y** [comment] 2019-03-28 18:47
Thanks for the patch to handle screen initialization gracefully. It seems like this is a good solution for now, fixing all of the color issues on all terminals is a larger issue than this project tries to solve.

Looks like konsole does not implement changing color definitions [seen here](https://stackoverflow.com/a/35759060/5680070).

Though it does appear that things like htop and vim display colors correctly in konsole and st, htop uses ncurses and vim does not(as far as I know), so there must be a solution out there.

Also, thank you for the link to your project! It's exciting seeing this library being used outside of my own projects :)

**Closed by a-n-t-h-o-n-y** 2019-03-28 18:47 UTC
